### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by halostatue** [ajvondrak/bitwise_ip#1]
I’m looking to release https://github.com/KineticCafe/ip_access_control, but I don’t want to do so with a `git` dependency. This looks like it’s good for a release, to me.

**Comment by ajvondrak** [comment]
Hey, sorry I dropped off there. I was working on documenting things, but life caught up to me. I just pushed the local changes I had. I believe all that's left to document is the `BitwiseIp.Blocks` module. A useful README would also be nice. Since it's close anyway, and I'd hate to release something that's _almost_ done, I'm going to see if I can power through those to-dos and cut the v1.0.0 soon™.

**Comment by halostatue** [comment]
I got busy, too. I only had a little bit of time pop up in the last couple of days.

**Comment by ajvondrak** [comment]
Released: https://hex.pm/packages/bitwise_ip 🎉 

Note that I renamed `BitwiseIp.Blocks.contain?/2` to `BitwiseIp.Blocks.member?/2`. Felt like it was a better name at the last minute. 😅 

Let me know if there are any problems!
